export const LOADING = 'LOADING'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_CATEGORY = 'SET_CATEGORY'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'

// MANAGING CATEGORIES
export const CAT_LOADING = 'CAT_LOADING'
export const EDIT_CATEGORY_MODAL_CLOSE = 'EDIT_CATEGORY_MODAL_CLOSE'
export const EDIT_CATEGORY_MODAL_OPEN = 'EDIT_CATEGORY_MODAL_OPEN'
export const ADD_CATEGORY_MODAL = 'ADD_CATEGORY_MODAL'
export const FETCH_CATEGORY_AND_CHANGE_STATE = 'FETCH_CATEGORY_AND_CHANGE_STATE'