export const LOADING = 'LOADING'
export const MENU = 'MENU'
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS'

// MANAGE PRODUCTS
export const FETCH_PRODUCTS_AND_CHANGE_STATE = 'FETCH_PRODUCTS_AND_CHANGE_STATE'
export const ADD_PRODUCT_MODAL = 'ADD_PRODUCT_MODAL'
export const EDIT_PRODUCT_MODAL_OPEN = 'EDIT_PRODUCT_MODAL_OPEN'
export const EDIT_PRODUCT_MODAL_CLOSE = 'EDIT_PRODUCT_MODAL_CLOSE'
export const PRODUCT_LOADING = 'PRODUCT_LOADING'